// Generated by gencpp from file rei_robot_cruise/NavGoal.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_CRUISE_MESSAGE_NAVGOAL_H
#define REI_ROBOT_CRUISE_MESSAGE_NAVGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace rei_robot_cruise
{
template <class ContainerAllocator>
struct NavGoal_
{
  typedef NavGoal_<ContainerAllocator> Type;

  NavGoal_()
    : point_name()
    , level(0)
    , target_pose()  {
    }
  NavGoal_(const ContainerAllocator& _alloc)
    : point_name(_alloc)
    , level(0)
    , target_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _point_name_type;
  _point_name_type point_name;

   typedef int8_t _level_type;
  _level_type level;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;





  typedef boost::shared_ptr< ::rei_robot_cruise::NavGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rei_robot_cruise::NavGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NavGoal_

typedef ::rei_robot_cruise::NavGoal_<std::allocator<void> > NavGoal;

typedef boost::shared_ptr< ::rei_robot_cruise::NavGoal > NavGoalPtr;
typedef boost::shared_ptr< ::rei_robot_cruise::NavGoal const> NavGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rei_robot_cruise::NavGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rei_robot_cruise::NavGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rei_robot_cruise::NavGoal_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::NavGoal_<ContainerAllocator2> & rhs)
{
  return lhs.point_name == rhs.point_name &&
    lhs.level == rhs.level &&
    lhs.target_pose == rhs.target_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rei_robot_cruise::NavGoal_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::NavGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rei_robot_cruise

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::NavGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::NavGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::NavGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::NavGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::NavGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::NavGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rei_robot_cruise::NavGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76079389e9944c93b7011c612b3a9d95";
  }

  static const char* value(const ::rei_robot_cruise::NavGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76079389e9944c93ULL;
  static const uint64_t static_value2 = 0xb7011c612b3a9d95ULL;
};

template<class ContainerAllocator>
struct DataType< ::rei_robot_cruise::NavGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rei_robot_cruise/NavGoal";
  }

  static const char* value(const ::rei_robot_cruise::NavGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rei_robot_cruise::NavGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string point_name\n"
"int8 level #0: can be ignore, 1: important\n"
"geometry_msgs/PoseStamped target_pose\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rei_robot_cruise::NavGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rei_robot_cruise::NavGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point_name);
      stream.next(m.level);
      stream.next(m.target_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rei_robot_cruise::NavGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rei_robot_cruise::NavGoal_<ContainerAllocator>& v)
  {
    s << indent << "point_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.point_name);
    s << indent << "level: ";
    Printer<int8_t>::stream(s, indent + "  ", v.level);
    s << indent << "target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REI_ROBOT_CRUISE_MESSAGE_NAVGOAL_H
