// Generated by gencpp from file rei_robot_cruise/RemoveGoalRequest.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_CRUISE_MESSAGE_REMOVEGOALREQUEST_H
#define REI_ROBOT_CRUISE_MESSAGE_REMOVEGOALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rei_robot_cruise
{
template <class ContainerAllocator>
struct RemoveGoalRequest_
{
  typedef RemoveGoalRequest_<ContainerAllocator> Type;

  RemoveGoalRequest_()
    : mode()
    , goal_names()  {
    }
  RemoveGoalRequest_(const ContainerAllocator& _alloc)
    : mode(_alloc)
    , goal_names(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mode_type;
  _mode_type mode;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _goal_names_type;
  _goal_names_type goal_names;





  typedef boost::shared_ptr< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RemoveGoalRequest_

typedef ::rei_robot_cruise::RemoveGoalRequest_<std::allocator<void> > RemoveGoalRequest;

typedef boost::shared_ptr< ::rei_robot_cruise::RemoveGoalRequest > RemoveGoalRequestPtr;
typedef boost::shared_ptr< ::rei_robot_cruise::RemoveGoalRequest const> RemoveGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.goal_names == rhs.goal_names;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rei_robot_cruise

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06feb05819d929d5724cad4e481ea459";
  }

  static const char* value(const ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06feb05819d929d5ULL;
  static const uint64_t static_value2 = 0x724cad4e481ea459ULL;
};

template<class ContainerAllocator>
struct DataType< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rei_robot_cruise/RemoveGoalRequest";
  }

  static const char* value(const ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mode #\"all\"/\"not_all\"\n"
"string[] goal_names#if mode is \"not all\"\n"
;
  }

  static const char* value(const ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.goal_names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoveGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rei_robot_cruise::RemoveGoalRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mode);
    s << indent << "goal_names[]" << std::endl;
    for (size_t i = 0; i < v.goal_names.size(); ++i)
    {
      s << indent << "  goal_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.goal_names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REI_ROBOT_CRUISE_MESSAGE_REMOVEGOALREQUEST_H
