// Generated by gencpp from file rei_robot_cruise/SetGoalsResponse.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_CRUISE_MESSAGE_SETGOALSRESPONSE_H
#define REI_ROBOT_CRUISE_MESSAGE_SETGOALSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rei_robot_cruise
{
template <class ContainerAllocator>
struct SetGoalsResponse_
{
  typedef SetGoalsResponse_<ContainerAllocator> Type;

  SetGoalsResponse_()
    : isSuccess(false)  {
    }
  SetGoalsResponse_(const ContainerAllocator& _alloc)
    : isSuccess(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isSuccess_type;
  _isSuccess_type isSuccess;





  typedef boost::shared_ptr< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetGoalsResponse_

typedef ::rei_robot_cruise::SetGoalsResponse_<std::allocator<void> > SetGoalsResponse;

typedef boost::shared_ptr< ::rei_robot_cruise::SetGoalsResponse > SetGoalsResponsePtr;
typedef boost::shared_ptr< ::rei_robot_cruise::SetGoalsResponse const> SetGoalsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.isSuccess == rhs.isSuccess;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rei_robot_cruise

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7dbd1de57ef8fd16c2d4ef28e12e701";
  }

  static const char* value(const ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7dbd1de57ef8fd1ULL;
  static const uint64_t static_value2 = 0x6c2d4ef28e12e701ULL;
};

template<class ContainerAllocator>
struct DataType< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rei_robot_cruise/SetGoalsResponse";
  }

  static const char* value(const ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isSuccess\n"
;
  }

  static const char* value(const ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isSuccess);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGoalsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rei_robot_cruise::SetGoalsResponse_<ContainerAllocator>& v)
  {
    s << indent << "isSuccess: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isSuccess);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REI_ROBOT_CRUISE_MESSAGE_SETGOALSRESPONSE_H
