// Generated by gencpp from file rei_robot_cruise/SetGoals.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_CRUISE_MESSAGE_SETGOALS_H
#define REI_ROBOT_CRUISE_MESSAGE_SETGOALS_H

#include <ros/service_traits.h>


#include <rei_robot_cruise/SetGoalsRequest.h>
#include <rei_robot_cruise/SetGoalsResponse.h>


namespace rei_robot_cruise
{

struct SetGoals
{

typedef SetGoalsRequest Request;
typedef SetGoalsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGoals
} // namespace rei_robot_cruise


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rei_robot_cruise::SetGoals > {
  static const char* value()
  {
    return "0fc3a7c0031cb18f49e9f325b3d8fbf4";
  }

  static const char* value(const ::rei_robot_cruise::SetGoals&) { return value(); }
};

template<>
struct DataType< ::rei_robot_cruise::SetGoals > {
  static const char* value()
  {
    return "rei_robot_cruise/SetGoals";
  }

  static const char* value(const ::rei_robot_cruise::SetGoals&) { return value(); }
};


// service_traits::MD5Sum< ::rei_robot_cruise::SetGoalsRequest> should match
// service_traits::MD5Sum< ::rei_robot_cruise::SetGoals >
template<>
struct MD5Sum< ::rei_robot_cruise::SetGoalsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rei_robot_cruise::SetGoals >::value();
  }
  static const char* value(const ::rei_robot_cruise::SetGoalsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rei_robot_cruise::SetGoalsRequest> should match
// service_traits::DataType< ::rei_robot_cruise::SetGoals >
template<>
struct DataType< ::rei_robot_cruise::SetGoalsRequest>
{
  static const char* value()
  {
    return DataType< ::rei_robot_cruise::SetGoals >::value();
  }
  static const char* value(const ::rei_robot_cruise::SetGoalsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rei_robot_cruise::SetGoalsResponse> should match
// service_traits::MD5Sum< ::rei_robot_cruise::SetGoals >
template<>
struct MD5Sum< ::rei_robot_cruise::SetGoalsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rei_robot_cruise::SetGoals >::value();
  }
  static const char* value(const ::rei_robot_cruise::SetGoalsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rei_robot_cruise::SetGoalsResponse> should match
// service_traits::DataType< ::rei_robot_cruise::SetGoals >
template<>
struct DataType< ::rei_robot_cruise::SetGoalsResponse>
{
  static const char* value()
  {
    return DataType< ::rei_robot_cruise::SetGoals >::value();
  }
  static const char* value(const ::rei_robot_cruise::SetGoalsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REI_ROBOT_CRUISE_MESSAGE_SETGOALS_H
