// Generated by gencpp from file rei_robot_cruise/SetGoalsRequest.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_CRUISE_MESSAGE_SETGOALSREQUEST_H
#define REI_ROBOT_CRUISE_MESSAGE_SETGOALSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rei_robot_cruise/NavGoal.h>

namespace rei_robot_cruise
{
template <class ContainerAllocator>
struct SetGoalsRequest_
{
  typedef SetGoalsRequest_<ContainerAllocator> Type;

  SetGoalsRequest_()
    : mode()
    , goals()  {
    }
  SetGoalsRequest_(const ContainerAllocator& _alloc)
    : mode(_alloc)
    , goals(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mode_type;
  _mode_type mode;

   typedef std::vector< ::rei_robot_cruise::NavGoal_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::rei_robot_cruise::NavGoal_<ContainerAllocator> >> _goals_type;
  _goals_type goals;





  typedef boost::shared_ptr< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetGoalsRequest_

typedef ::rei_robot_cruise::SetGoalsRequest_<std::allocator<void> > SetGoalsRequest;

typedef boost::shared_ptr< ::rei_robot_cruise::SetGoalsRequest > SetGoalsRequestPtr;
typedef boost::shared_ptr< ::rei_robot_cruise::SetGoalsRequest const> SetGoalsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.goals == rhs.goals;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rei_robot_cruise

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3db4d9f87473f68b2e5a5f0339c4699";
  }

  static const char* value(const ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3db4d9f87473f68ULL;
  static const uint64_t static_value2 = 0xb2e5a5f0339c4699ULL;
};

template<class ContainerAllocator>
struct DataType< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rei_robot_cruise/SetGoalsRequest";
  }

  static const char* value(const ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mode #'insert': insert new goal or replace the same name goal, \"reset\": remove all goals and add these goals \n"
"rei_robot_cruise/NavGoal[] goals\n"
"\n"
"================================================================================\n"
"MSG: rei_robot_cruise/NavGoal\n"
"string point_name\n"
"int8 level #0: can be ignore, 1: important\n"
"geometry_msgs/PoseStamped target_pose\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.goals);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGoalsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rei_robot_cruise::SetGoalsRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mode);
    s << indent << "goals[]" << std::endl;
    for (size_t i = 0; i < v.goals.size(); ++i)
    {
      s << indent << "  goals[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rei_robot_cruise::NavGoal_<ContainerAllocator> >::stream(s, indent + "    ", v.goals[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REI_ROBOT_CRUISE_MESSAGE_SETGOALSREQUEST_H
