// Generated by gencpp from file rei_robot_cruise/SetNavOrder.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_CRUISE_MESSAGE_SETNAVORDER_H
#define REI_ROBOT_CRUISE_MESSAGE_SETNAVORDER_H

#include <ros/service_traits.h>


#include <rei_robot_cruise/SetNavOrderRequest.h>
#include <rei_robot_cruise/SetNavOrderResponse.h>


namespace rei_robot_cruise
{

struct SetNavOrder
{

typedef SetNavOrderRequest Request;
typedef SetNavOrderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetNavOrder
} // namespace rei_robot_cruise


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rei_robot_cruise::SetNavOrder > {
  static const char* value()
  {
    return "40f5672c1f1f412d28deb80740b471de";
  }

  static const char* value(const ::rei_robot_cruise::SetNavOrder&) { return value(); }
};

template<>
struct DataType< ::rei_robot_cruise::SetNavOrder > {
  static const char* value()
  {
    return "rei_robot_cruise/SetNavOrder";
  }

  static const char* value(const ::rei_robot_cruise::SetNavOrder&) { return value(); }
};


// service_traits::MD5Sum< ::rei_robot_cruise::SetNavOrderRequest> should match
// service_traits::MD5Sum< ::rei_robot_cruise::SetNavOrder >
template<>
struct MD5Sum< ::rei_robot_cruise::SetNavOrderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rei_robot_cruise::SetNavOrder >::value();
  }
  static const char* value(const ::rei_robot_cruise::SetNavOrderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rei_robot_cruise::SetNavOrderRequest> should match
// service_traits::DataType< ::rei_robot_cruise::SetNavOrder >
template<>
struct DataType< ::rei_robot_cruise::SetNavOrderRequest>
{
  static const char* value()
  {
    return DataType< ::rei_robot_cruise::SetNavOrder >::value();
  }
  static const char* value(const ::rei_robot_cruise::SetNavOrderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rei_robot_cruise::SetNavOrderResponse> should match
// service_traits::MD5Sum< ::rei_robot_cruise::SetNavOrder >
template<>
struct MD5Sum< ::rei_robot_cruise::SetNavOrderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rei_robot_cruise::SetNavOrder >::value();
  }
  static const char* value(const ::rei_robot_cruise::SetNavOrderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rei_robot_cruise::SetNavOrderResponse> should match
// service_traits::DataType< ::rei_robot_cruise::SetNavOrder >
template<>
struct DataType< ::rei_robot_cruise::SetNavOrderResponse>
{
  static const char* value()
  {
    return DataType< ::rei_robot_cruise::SetNavOrder >::value();
  }
  static const char* value(const ::rei_robot_cruise::SetNavOrderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REI_ROBOT_CRUISE_MESSAGE_SETNAVORDER_H
