// Generated by gencpp from file rei_robot_cruise/SetNavOrderResponse.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_CRUISE_MESSAGE_SETNAVORDERRESPONSE_H
#define REI_ROBOT_CRUISE_MESSAGE_SETNAVORDERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rei_robot_cruise
{
template <class ContainerAllocator>
struct SetNavOrderResponse_
{
  typedef SetNavOrderResponse_<ContainerAllocator> Type;

  SetNavOrderResponse_()
    : message()
    , isSuccess(false)  {
    }
  SetNavOrderResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , isSuccess(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef uint8_t _isSuccess_type;
  _isSuccess_type isSuccess;





  typedef boost::shared_ptr< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetNavOrderResponse_

typedef ::rei_robot_cruise::SetNavOrderResponse_<std::allocator<void> > SetNavOrderResponse;

typedef boost::shared_ptr< ::rei_robot_cruise::SetNavOrderResponse > SetNavOrderResponsePtr;
typedef boost::shared_ptr< ::rei_robot_cruise::SetNavOrderResponse const> SetNavOrderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message &&
    lhs.isSuccess == rhs.isSuccess;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rei_robot_cruise

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d6a17e315b493a32a82070425a28084";
  }

  static const char* value(const ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d6a17e315b493a3ULL;
  static const uint64_t static_value2 = 0x2a82070425a28084ULL;
};

template<class ContainerAllocator>
struct DataType< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rei_robot_cruise/SetNavOrderResponse";
  }

  static const char* value(const ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"bool isSuccess\n"
;
  }

  static const char* value(const ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.isSuccess);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetNavOrderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rei_robot_cruise::SetNavOrderResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "isSuccess: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isSuccess);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REI_ROBOT_CRUISE_MESSAGE_SETNAVORDERRESPONSE_H
