// Generated by gencpp from file rei_robot_cruise/SetNavOrderRequest.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_CRUISE_MESSAGE_SETNAVORDERREQUEST_H
#define REI_ROBOT_CRUISE_MESSAGE_SETNAVORDERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rei_robot_cruise
{
template <class ContainerAllocator>
struct SetNavOrderRequest_
{
  typedef SetNavOrderRequest_<ContainerAllocator> Type;

  SetNavOrderRequest_()
    : loop_time(0)
    , goal_order()
    , callback_order()  {
    }
  SetNavOrderRequest_(const ContainerAllocator& _alloc)
    : loop_time(0)
    , goal_order(_alloc)
    , callback_order(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _loop_time_type;
  _loop_time_type loop_time;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _goal_order_type;
  _goal_order_type goal_order;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _callback_order_type;
  _callback_order_type callback_order;





  typedef boost::shared_ptr< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetNavOrderRequest_

typedef ::rei_robot_cruise::SetNavOrderRequest_<std::allocator<void> > SetNavOrderRequest;

typedef boost::shared_ptr< ::rei_robot_cruise::SetNavOrderRequest > SetNavOrderRequestPtr;
typedef boost::shared_ptr< ::rei_robot_cruise::SetNavOrderRequest const> SetNavOrderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator2> & rhs)
{
  return lhs.loop_time == rhs.loop_time &&
    lhs.goal_order == rhs.goal_order &&
    lhs.callback_order == rhs.callback_order;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rei_robot_cruise

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d3b07d1f11bc648bfe2a035409e32ae";
  }

  static const char* value(const ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d3b07d1f11bc648ULL;
  static const uint64_t static_value2 = 0xbfe2a035409e32aeULL;
};

template<class ContainerAllocator>
struct DataType< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rei_robot_cruise/SetNavOrderRequest";
  }

  static const char* value(const ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 loop_time #0 means infinite\n"
"string[] goal_order\n"
"string[] callback_order\n"
;
  }

  static const char* value(const ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.loop_time);
      stream.next(m.goal_order);
      stream.next(m.callback_order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetNavOrderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rei_robot_cruise::SetNavOrderRequest_<ContainerAllocator>& v)
  {
    s << indent << "loop_time: ";
    Printer<int16_t>::stream(s, indent + "  ", v.loop_time);
    s << indent << "goal_order[]" << std::endl;
    for (size_t i = 0; i < v.goal_order.size(); ++i)
    {
      s << indent << "  goal_order[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.goal_order[i]);
    }
    s << indent << "callback_order[]" << std::endl;
    for (size_t i = 0; i < v.callback_order.size(); ++i)
    {
      s << indent << "  callback_order[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.callback_order[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REI_ROBOT_CRUISE_MESSAGE_SETNAVORDERREQUEST_H
