// Generated by gencpp from file rei_robot_cruise/StartStopNav.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_CRUISE_MESSAGE_STARTSTOPNAV_H
#define REI_ROBOT_CRUISE_MESSAGE_STARTSTOPNAV_H

#include <ros/service_traits.h>


#include <rei_robot_cruise/StartStopNavRequest.h>
#include <rei_robot_cruise/StartStopNavResponse.h>


namespace rei_robot_cruise
{

struct StartStopNav
{

typedef StartStopNavRequest Request;
typedef StartStopNavResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartStopNav
} // namespace rei_robot_cruise


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rei_robot_cruise::StartStopNav > {
  static const char* value()
  {
    return "997ae050ff0c195c83d9c11c0633ef89";
  }

  static const char* value(const ::rei_robot_cruise::StartStopNav&) { return value(); }
};

template<>
struct DataType< ::rei_robot_cruise::StartStopNav > {
  static const char* value()
  {
    return "rei_robot_cruise/StartStopNav";
  }

  static const char* value(const ::rei_robot_cruise::StartStopNav&) { return value(); }
};


// service_traits::MD5Sum< ::rei_robot_cruise::StartStopNavRequest> should match
// service_traits::MD5Sum< ::rei_robot_cruise::StartStopNav >
template<>
struct MD5Sum< ::rei_robot_cruise::StartStopNavRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rei_robot_cruise::StartStopNav >::value();
  }
  static const char* value(const ::rei_robot_cruise::StartStopNavRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rei_robot_cruise::StartStopNavRequest> should match
// service_traits::DataType< ::rei_robot_cruise::StartStopNav >
template<>
struct DataType< ::rei_robot_cruise::StartStopNavRequest>
{
  static const char* value()
  {
    return DataType< ::rei_robot_cruise::StartStopNav >::value();
  }
  static const char* value(const ::rei_robot_cruise::StartStopNavRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rei_robot_cruise::StartStopNavResponse> should match
// service_traits::MD5Sum< ::rei_robot_cruise::StartStopNav >
template<>
struct MD5Sum< ::rei_robot_cruise::StartStopNavResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rei_robot_cruise::StartStopNav >::value();
  }
  static const char* value(const ::rei_robot_cruise::StartStopNavResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rei_robot_cruise::StartStopNavResponse> should match
// service_traits::DataType< ::rei_robot_cruise::StartStopNav >
template<>
struct DataType< ::rei_robot_cruise::StartStopNavResponse>
{
  static const char* value()
  {
    return DataType< ::rei_robot_cruise::StartStopNav >::value();
  }
  static const char* value(const ::rei_robot_cruise::StartStopNavResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REI_ROBOT_CRUISE_MESSAGE_STARTSTOPNAV_H
