// Generated by gencpp from file rei_robot_cruise/StartStopNavRequest.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_CRUISE_MESSAGE_STARTSTOPNAVREQUEST_H
#define REI_ROBOT_CRUISE_MESSAGE_STARTSTOPNAVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rei_robot_cruise
{
template <class ContainerAllocator>
struct StartStopNavRequest_
{
  typedef StartStopNavRequest_<ContainerAllocator> Type;

  StartStopNavRequest_()
    : mode()
    , level(0)  {
    }
  StartStopNavRequest_(const ContainerAllocator& _alloc)
    : mode(_alloc)
    , level(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mode_type;
  _mode_type mode;

   typedef int8_t _level_type;
  _level_type level;





  typedef boost::shared_ptr< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartStopNavRequest_

typedef ::rei_robot_cruise::StartStopNavRequest_<std::allocator<void> > StartStopNavRequest;

typedef boost::shared_ptr< ::rei_robot_cruise::StartStopNavRequest > StartStopNavRequestPtr;
typedef boost::shared_ptr< ::rei_robot_cruise::StartStopNavRequest const> StartStopNavRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.level == rhs.level;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator1> & lhs, const ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rei_robot_cruise

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "997a3f36b2d8122812c76a190a1c6e40";
  }

  static const char* value(const ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x997a3f36b2d81228ULL;
  static const uint64_t static_value2 = 0x12c76a190a1c6e40ULL;
};

template<class ContainerAllocator>
struct DataType< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rei_robot_cruise/StartStopNavRequest";
  }

  static const char* value(const ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mode #'stop':stop the task, 'paush': paush the task, \"start\"\n"
"int8 level #'0': action after current goal finished, '1':action immediately\n"
;
  }

  static const char* value(const ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.level);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartStopNavRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rei_robot_cruise::StartStopNavRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mode);
    s << indent << "level: ";
    Printer<int8_t>::stream(s, indent + "  ", v.level);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REI_ROBOT_CRUISE_MESSAGE_STARTSTOPNAVREQUEST_H
