// Generated by gencpp from file rei_robot_base/BumperCliff.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_BASE_MESSAGE_BUMPERCLIFF_H
#define REI_ROBOT_BASE_MESSAGE_BUMPERCLIFF_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rei_robot_base
{
template <class ContainerAllocator>
struct BumperCliff_
{
  typedef BumperCliff_<ContainerAllocator> Type;

  BumperCliff_()
    : header()
    , bumper(false)
    , cliff(false)  {
    }
  BumperCliff_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bumper(false)
    , cliff(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _bumper_type;
  _bumper_type bumper;

   typedef uint8_t _cliff_type;
  _cliff_type cliff;





  typedef boost::shared_ptr< ::rei_robot_base::BumperCliff_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rei_robot_base::BumperCliff_<ContainerAllocator> const> ConstPtr;

}; // struct BumperCliff_

typedef ::rei_robot_base::BumperCliff_<std::allocator<void> > BumperCliff;

typedef boost::shared_ptr< ::rei_robot_base::BumperCliff > BumperCliffPtr;
typedef boost::shared_ptr< ::rei_robot_base::BumperCliff const> BumperCliffConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rei_robot_base::BumperCliff_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rei_robot_base::BumperCliff_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rei_robot_base::BumperCliff_<ContainerAllocator1> & lhs, const ::rei_robot_base::BumperCliff_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.bumper == rhs.bumper &&
    lhs.cliff == rhs.cliff;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rei_robot_base::BumperCliff_<ContainerAllocator1> & lhs, const ::rei_robot_base::BumperCliff_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rei_robot_base

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_base::BumperCliff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_base::BumperCliff_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_base::BumperCliff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_base::BumperCliff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_base::BumperCliff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_base::BumperCliff_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rei_robot_base::BumperCliff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab6287bf4b996386da4b9c24cd2a59f3";
  }

  static const char* value(const ::rei_robot_base::BumperCliff_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab6287bf4b996386ULL;
  static const uint64_t static_value2 = 0xda4b9c24cd2a59f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rei_robot_base::BumperCliff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rei_robot_base/BumperCliff";
  }

  static const char* value(const ::rei_robot_base::BumperCliff_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rei_robot_base::BumperCliff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool bumper\n"
"bool cliff\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rei_robot_base::BumperCliff_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rei_robot_base::BumperCliff_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bumper);
      stream.next(m.cliff);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BumperCliff_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rei_robot_base::BumperCliff_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rei_robot_base::BumperCliff_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bumper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bumper);
    s << indent << "cliff: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cliff);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REI_ROBOT_BASE_MESSAGE_BUMPERCLIFF_H
