// Generated by gencpp from file rei_robot_base/CarData.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_BASE_MESSAGE_CARDATA_H
#define REI_ROBOT_BASE_MESSAGE_CARDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rei_robot_base
{
template <class ContainerAllocator>
struct CarData_
{
  typedef CarData_<ContainerAllocator> Type;

  CarData_()
    : header()
    , motor_speed()
    , crash()
    , cliff()
    , ultrasound()
    , smoke(0)
    , power_voltage(0.0)
    , is_charge(false)
    , tempareture(0.0)
    , relative_humidity(0.0)
    , input_io()
    , output_io()
    , relay_status(false)  {
      input_io.assign(0);

      output_io.assign(0);
  }
  CarData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , motor_speed(_alloc)
    , crash(_alloc)
    , cliff(_alloc)
    , ultrasound(_alloc)
    , smoke(0)
    , power_voltage(0.0)
    , is_charge(false)
    , tempareture(0.0)
    , relative_humidity(0.0)
    , input_io()
    , output_io()
    , relay_status(false)  {
  (void)_alloc;
      input_io.assign(0);

      output_io.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _motor_speed_type;
  _motor_speed_type motor_speed;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _crash_type;
  _crash_type crash;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _cliff_type;
  _cliff_type cliff;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _ultrasound_type;
  _ultrasound_type ultrasound;

   typedef int8_t _smoke_type;
  _smoke_type smoke;

   typedef float _power_voltage_type;
  _power_voltage_type power_voltage;

   typedef uint8_t _is_charge_type;
  _is_charge_type is_charge;

   typedef float _tempareture_type;
  _tempareture_type tempareture;

   typedef float _relative_humidity_type;
  _relative_humidity_type relative_humidity;

   typedef boost::array<int8_t, 4>  _input_io_type;
  _input_io_type input_io;

   typedef boost::array<int8_t, 7>  _output_io_type;
  _output_io_type output_io;

   typedef uint8_t _relay_status_type;
  _relay_status_type relay_status;





  typedef boost::shared_ptr< ::rei_robot_base::CarData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rei_robot_base::CarData_<ContainerAllocator> const> ConstPtr;

}; // struct CarData_

typedef ::rei_robot_base::CarData_<std::allocator<void> > CarData;

typedef boost::shared_ptr< ::rei_robot_base::CarData > CarDataPtr;
typedef boost::shared_ptr< ::rei_robot_base::CarData const> CarDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rei_robot_base::CarData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rei_robot_base::CarData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rei_robot_base::CarData_<ContainerAllocator1> & lhs, const ::rei_robot_base::CarData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.motor_speed == rhs.motor_speed &&
    lhs.crash == rhs.crash &&
    lhs.cliff == rhs.cliff &&
    lhs.ultrasound == rhs.ultrasound &&
    lhs.smoke == rhs.smoke &&
    lhs.power_voltage == rhs.power_voltage &&
    lhs.is_charge == rhs.is_charge &&
    lhs.tempareture == rhs.tempareture &&
    lhs.relative_humidity == rhs.relative_humidity &&
    lhs.input_io == rhs.input_io &&
    lhs.output_io == rhs.output_io &&
    lhs.relay_status == rhs.relay_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rei_robot_base::CarData_<ContainerAllocator1> & lhs, const ::rei_robot_base::CarData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rei_robot_base

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_base::CarData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_base::CarData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_base::CarData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_base::CarData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_base::CarData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_base::CarData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rei_robot_base::CarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "857f5bd49eb52154124a6a34972c8da9";
  }

  static const char* value(const ::rei_robot_base::CarData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x857f5bd49eb52154ULL;
  static const uint64_t static_value2 = 0x124a6a34972c8da9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rei_robot_base::CarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rei_robot_base/CarData";
  }

  static const char* value(const ::rei_robot_base::CarData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rei_robot_base::CarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64[] motor_speed\n"
"int8[] crash\n"
"int8[] cliff\n"
"float32[] ultrasound\n"
"int8 smoke\n"
"float32 power_voltage\n"
"bool is_charge\n"
"float32 tempareture\n"
"float32 relative_humidity\n"
"int8[4] input_io\n"
"int8[7] output_io\n"
"bool relay_status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rei_robot_base::CarData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rei_robot_base::CarData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.motor_speed);
      stream.next(m.crash);
      stream.next(m.cliff);
      stream.next(m.ultrasound);
      stream.next(m.smoke);
      stream.next(m.power_voltage);
      stream.next(m.is_charge);
      stream.next(m.tempareture);
      stream.next(m.relative_humidity);
      stream.next(m.input_io);
      stream.next(m.output_io);
      stream.next(m.relay_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rei_robot_base::CarData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rei_robot_base::CarData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motor_speed[]" << std::endl;
    for (size_t i = 0; i < v.motor_speed.size(); ++i)
    {
      s << indent << "  motor_speed[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.motor_speed[i]);
    }
    s << indent << "crash[]" << std::endl;
    for (size_t i = 0; i < v.crash.size(); ++i)
    {
      s << indent << "  crash[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.crash[i]);
    }
    s << indent << "cliff[]" << std::endl;
    for (size_t i = 0; i < v.cliff.size(); ++i)
    {
      s << indent << "  cliff[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.cliff[i]);
    }
    s << indent << "ultrasound[]" << std::endl;
    for (size_t i = 0; i < v.ultrasound.size(); ++i)
    {
      s << indent << "  ultrasound[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ultrasound[i]);
    }
    s << indent << "smoke: ";
    Printer<int8_t>::stream(s, indent + "  ", v.smoke);
    s << indent << "power_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.power_voltage);
    s << indent << "is_charge: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_charge);
    s << indent << "tempareture: ";
    Printer<float>::stream(s, indent + "  ", v.tempareture);
    s << indent << "relative_humidity: ";
    Printer<float>::stream(s, indent + "  ", v.relative_humidity);
    s << indent << "input_io[]" << std::endl;
    for (size_t i = 0; i < v.input_io.size(); ++i)
    {
      s << indent << "  input_io[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.input_io[i]);
    }
    s << indent << "output_io[]" << std::endl;
    for (size_t i = 0; i < v.output_io.size(); ++i)
    {
      s << indent << "  output_io[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.output_io[i]);
    }
    s << indent << "relay_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relay_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REI_ROBOT_BASE_MESSAGE_CARDATA_H
