// Generated by gencpp from file rei_robot_base/Int8.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_BASE_MESSAGE_INT8_H
#define REI_ROBOT_BASE_MESSAGE_INT8_H

#include <ros/service_traits.h>


#include <rei_robot_base/Int8Request.h>
#include <rei_robot_base/Int8Response.h>


namespace rei_robot_base
{

struct Int8
{

typedef Int8Request Request;
typedef Int8Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Int8
} // namespace rei_robot_base


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rei_robot_base::Int8 > {
  static const char* value()
  {
    return "208d4ab53cf12eb941a7d93b34b7532b";
  }

  static const char* value(const ::rei_robot_base::Int8&) { return value(); }
};

template<>
struct DataType< ::rei_robot_base::Int8 > {
  static const char* value()
  {
    return "rei_robot_base/Int8";
  }

  static const char* value(const ::rei_robot_base::Int8&) { return value(); }
};


// service_traits::MD5Sum< ::rei_robot_base::Int8Request> should match
// service_traits::MD5Sum< ::rei_robot_base::Int8 >
template<>
struct MD5Sum< ::rei_robot_base::Int8Request>
{
  static const char* value()
  {
    return MD5Sum< ::rei_robot_base::Int8 >::value();
  }
  static const char* value(const ::rei_robot_base::Int8Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::rei_robot_base::Int8Request> should match
// service_traits::DataType< ::rei_robot_base::Int8 >
template<>
struct DataType< ::rei_robot_base::Int8Request>
{
  static const char* value()
  {
    return DataType< ::rei_robot_base::Int8 >::value();
  }
  static const char* value(const ::rei_robot_base::Int8Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rei_robot_base::Int8Response> should match
// service_traits::MD5Sum< ::rei_robot_base::Int8 >
template<>
struct MD5Sum< ::rei_robot_base::Int8Response>
{
  static const char* value()
  {
    return MD5Sum< ::rei_robot_base::Int8 >::value();
  }
  static const char* value(const ::rei_robot_base::Int8Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::rei_robot_base::Int8Response> should match
// service_traits::DataType< ::rei_robot_base::Int8 >
template<>
struct DataType< ::rei_robot_base::Int8Response>
{
  static const char* value()
  {
    return DataType< ::rei_robot_base::Int8 >::value();
  }
  static const char* value(const ::rei_robot_base::Int8Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REI_ROBOT_BASE_MESSAGE_INT8_H
