// Generated by gencpp from file rei_robot_base/Int8Request.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_BASE_MESSAGE_INT8REQUEST_H
#define REI_ROBOT_BASE_MESSAGE_INT8REQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rei_robot_base
{
template <class ContainerAllocator>
struct Int8Request_
{
  typedef Int8Request_<ContainerAllocator> Type;

  Int8Request_()
    : data(0)  {
    }
  Int8Request_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::rei_robot_base::Int8Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rei_robot_base::Int8Request_<ContainerAllocator> const> ConstPtr;

}; // struct Int8Request_

typedef ::rei_robot_base::Int8Request_<std::allocator<void> > Int8Request;

typedef boost::shared_ptr< ::rei_robot_base::Int8Request > Int8RequestPtr;
typedef boost::shared_ptr< ::rei_robot_base::Int8Request const> Int8RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rei_robot_base::Int8Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rei_robot_base::Int8Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rei_robot_base::Int8Request_<ContainerAllocator1> & lhs, const ::rei_robot_base::Int8Request_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rei_robot_base::Int8Request_<ContainerAllocator1> & lhs, const ::rei_robot_base::Int8Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rei_robot_base

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_base::Int8Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_base::Int8Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_base::Int8Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_base::Int8Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_base::Int8Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_base::Int8Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rei_robot_base::Int8Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27ffa0c9c4b8fb8492252bcad9e5c57b";
  }

  static const char* value(const ::rei_robot_base::Int8Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27ffa0c9c4b8fb84ULL;
  static const uint64_t static_value2 = 0x92252bcad9e5c57bULL;
};

template<class ContainerAllocator>
struct DataType< ::rei_robot_base::Int8Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rei_robot_base/Int8Request";
  }

  static const char* value(const ::rei_robot_base::Int8Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rei_robot_base::Int8Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 data\n"
;
  }

  static const char* value(const ::rei_robot_base::Int8Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rei_robot_base::Int8Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Int8Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rei_robot_base::Int8Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rei_robot_base::Int8Request_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REI_ROBOT_BASE_MESSAGE_INT8REQUEST_H
