// Generated by gencpp from file rei_robot_base/MotorCmd.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_BASE_MESSAGE_MOTORCMD_H
#define REI_ROBOT_BASE_MESSAGE_MOTORCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rei_robot_base
{
template <class ContainerAllocator>
struct MotorCmd_
{
  typedef MotorCmd_<ContainerAllocator> Type;

  MotorCmd_()
    : header()
    , motor_expect_speed()  {
    }
  MotorCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , motor_expect_speed(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _motor_expect_speed_type;
  _motor_expect_speed_type motor_expect_speed;





  typedef boost::shared_ptr< ::rei_robot_base::MotorCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rei_robot_base::MotorCmd_<ContainerAllocator> const> ConstPtr;

}; // struct MotorCmd_

typedef ::rei_robot_base::MotorCmd_<std::allocator<void> > MotorCmd;

typedef boost::shared_ptr< ::rei_robot_base::MotorCmd > MotorCmdPtr;
typedef boost::shared_ptr< ::rei_robot_base::MotorCmd const> MotorCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rei_robot_base::MotorCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rei_robot_base::MotorCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rei_robot_base::MotorCmd_<ContainerAllocator1> & lhs, const ::rei_robot_base::MotorCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.motor_expect_speed == rhs.motor_expect_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rei_robot_base::MotorCmd_<ContainerAllocator1> & lhs, const ::rei_robot_base::MotorCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rei_robot_base

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_base::MotorCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_base::MotorCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_base::MotorCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_base::MotorCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_base::MotorCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_base::MotorCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rei_robot_base::MotorCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a2942428c5f1b0d3e058b2b6e137632";
  }

  static const char* value(const ::rei_robot_base::MotorCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a2942428c5f1b0dULL;
  static const uint64_t static_value2 = 0x3e058b2b6e137632ULL;
};

template<class ContainerAllocator>
struct DataType< ::rei_robot_base::MotorCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rei_robot_base/MotorCmd";
  }

  static const char* value(const ::rei_robot_base::MotorCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rei_robot_base::MotorCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64[] motor_expect_speed\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rei_robot_base::MotorCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rei_robot_base::MotorCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.motor_expect_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rei_robot_base::MotorCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rei_robot_base::MotorCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motor_expect_speed[]" << std::endl;
    for (size_t i = 0; i < v.motor_expect_speed.size(); ++i)
    {
      s << indent << "  motor_expect_speed[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.motor_expect_speed[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REI_ROBOT_BASE_MESSAGE_MOTORCMD_H
