// Generated by gencpp from file rei_robot_base/SetIO.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_BASE_MESSAGE_SETIO_H
#define REI_ROBOT_BASE_MESSAGE_SETIO_H

#include <ros/service_traits.h>


#include <rei_robot_base/SetIORequest.h>
#include <rei_robot_base/SetIOResponse.h>


namespace rei_robot_base
{

struct SetIO
{

typedef SetIORequest Request;
typedef SetIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetIO
} // namespace rei_robot_base


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rei_robot_base::SetIO > {
  static const char* value()
  {
    return "070183f95a96810ab8072eb2bc773618";
  }

  static const char* value(const ::rei_robot_base::SetIO&) { return value(); }
};

template<>
struct DataType< ::rei_robot_base::SetIO > {
  static const char* value()
  {
    return "rei_robot_base/SetIO";
  }

  static const char* value(const ::rei_robot_base::SetIO&) { return value(); }
};


// service_traits::MD5Sum< ::rei_robot_base::SetIORequest> should match
// service_traits::MD5Sum< ::rei_robot_base::SetIO >
template<>
struct MD5Sum< ::rei_robot_base::SetIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::rei_robot_base::SetIO >::value();
  }
  static const char* value(const ::rei_robot_base::SetIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rei_robot_base::SetIORequest> should match
// service_traits::DataType< ::rei_robot_base::SetIO >
template<>
struct DataType< ::rei_robot_base::SetIORequest>
{
  static const char* value()
  {
    return DataType< ::rei_robot_base::SetIO >::value();
  }
  static const char* value(const ::rei_robot_base::SetIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rei_robot_base::SetIOResponse> should match
// service_traits::MD5Sum< ::rei_robot_base::SetIO >
template<>
struct MD5Sum< ::rei_robot_base::SetIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rei_robot_base::SetIO >::value();
  }
  static const char* value(const ::rei_robot_base::SetIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rei_robot_base::SetIOResponse> should match
// service_traits::DataType< ::rei_robot_base::SetIO >
template<>
struct DataType< ::rei_robot_base::SetIOResponse>
{
  static const char* value()
  {
    return DataType< ::rei_robot_base::SetIO >::value();
  }
  static const char* value(const ::rei_robot_base::SetIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REI_ROBOT_BASE_MESSAGE_SETIO_H
