// Generated by gencpp from file rei_robot_base/SetIORequest.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_BASE_MESSAGE_SETIOREQUEST_H
#define REI_ROBOT_BASE_MESSAGE_SETIOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rei_robot_base
{
template <class ContainerAllocator>
struct SetIORequest_
{
  typedef SetIORequest_<ContainerAllocator> Type;

  SetIORequest_()
    : all_off(false)
    , all_on(false)
    , io()
    , state(false)  {
    }
  SetIORequest_(const ContainerAllocator& _alloc)
    : all_off(false)
    , all_on(false)
    , io(_alloc)
    , state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _all_off_type;
  _all_off_type all_off;

   typedef uint8_t _all_on_type;
  _all_on_type all_on;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _io_type;
  _io_type io;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::rei_robot_base::SetIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rei_robot_base::SetIORequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetIORequest_

typedef ::rei_robot_base::SetIORequest_<std::allocator<void> > SetIORequest;

typedef boost::shared_ptr< ::rei_robot_base::SetIORequest > SetIORequestPtr;
typedef boost::shared_ptr< ::rei_robot_base::SetIORequest const> SetIORequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rei_robot_base::SetIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rei_robot_base::SetIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rei_robot_base::SetIORequest_<ContainerAllocator1> & lhs, const ::rei_robot_base::SetIORequest_<ContainerAllocator2> & rhs)
{
  return lhs.all_off == rhs.all_off &&
    lhs.all_on == rhs.all_on &&
    lhs.io == rhs.io &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rei_robot_base::SetIORequest_<ContainerAllocator1> & lhs, const ::rei_robot_base::SetIORequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rei_robot_base

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_base::SetIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_base::SetIORequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_base::SetIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_base::SetIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_base::SetIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_base::SetIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rei_robot_base::SetIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8108254469eb756f3c04bf3424c3528";
  }

  static const char* value(const ::rei_robot_base::SetIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8108254469eb756ULL;
  static const uint64_t static_value2 = 0xf3c04bf3424c3528ULL;
};

template<class ContainerAllocator>
struct DataType< ::rei_robot_base::SetIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rei_robot_base/SetIORequest";
  }

  static const char* value(const ::rei_robot_base::SetIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rei_robot_base::SetIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool all_off\n"
"bool all_on \n"
"int8[] io\n"
"bool state\n"
;
  }

  static const char* value(const ::rei_robot_base::SetIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rei_robot_base::SetIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.all_off);
      stream.next(m.all_on);
      stream.next(m.io);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rei_robot_base::SetIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rei_robot_base::SetIORequest_<ContainerAllocator>& v)
  {
    s << indent << "all_off: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.all_off);
    s << indent << "all_on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.all_on);
    s << indent << "io[]" << std::endl;
    for (size_t i = 0; i < v.io.size(); ++i)
    {
      s << indent << "  io[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.io[i]);
    }
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REI_ROBOT_BASE_MESSAGE_SETIOREQUEST_H
