// Generated by gencpp from file rei_robot_base/SetIOResponse.msg
// DO NOT EDIT!


#ifndef REI_ROBOT_BASE_MESSAGE_SETIORESPONSE_H
#define REI_ROBOT_BASE_MESSAGE_SETIORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rei_robot_base
{
template <class ContainerAllocator>
struct SetIOResponse_
{
  typedef SetIOResponse_<ContainerAllocator> Type;

  SetIOResponse_()
    : success(false)
    , message()  {
    }
  SetIOResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::rei_robot_base::SetIOResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rei_robot_base::SetIOResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetIOResponse_

typedef ::rei_robot_base::SetIOResponse_<std::allocator<void> > SetIOResponse;

typedef boost::shared_ptr< ::rei_robot_base::SetIOResponse > SetIOResponsePtr;
typedef boost::shared_ptr< ::rei_robot_base::SetIOResponse const> SetIOResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rei_robot_base::SetIOResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rei_robot_base::SetIOResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rei_robot_base::SetIOResponse_<ContainerAllocator1> & lhs, const ::rei_robot_base::SetIOResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rei_robot_base::SetIOResponse_<ContainerAllocator1> & lhs, const ::rei_robot_base::SetIOResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rei_robot_base

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_base::SetIOResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rei_robot_base::SetIOResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_base::SetIOResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rei_robot_base::SetIOResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_base::SetIOResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rei_robot_base::SetIOResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rei_robot_base::SetIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::rei_robot_base::SetIOResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::rei_robot_base::SetIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rei_robot_base/SetIOResponse";
  }

  static const char* value(const ::rei_robot_base::SetIOResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rei_robot_base::SetIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::rei_robot_base::SetIOResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rei_robot_base::SetIOResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetIOResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rei_robot_base::SetIOResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rei_robot_base::SetIOResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REI_ROBOT_BASE_MESSAGE_SETIORESPONSE_H
