// Generated by gencpp from file auto_charging/SetChargeRequest.msg
// DO NOT EDIT!


#ifndef AUTO_CHARGING_MESSAGE_SETCHARGEREQUEST_H
#define AUTO_CHARGING_MESSAGE_SETCHARGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_charging
{
template <class ContainerAllocator>
struct SetChargeRequest_
{
  typedef SetChargeRequest_<ContainerAllocator> Type;

  SetChargeRequest_()
    : nav(false)
    , ar_track(false)
    , ar_id(0)  {
    }
  SetChargeRequest_(const ContainerAllocator& _alloc)
    : nav(false)
    , ar_track(false)
    , ar_id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _nav_type;
  _nav_type nav;

   typedef uint8_t _ar_track_type;
  _ar_track_type ar_track;

   typedef int8_t _ar_id_type;
  _ar_id_type ar_id;





  typedef boost::shared_ptr< ::auto_charging::SetChargeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_charging::SetChargeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetChargeRequest_

typedef ::auto_charging::SetChargeRequest_<std::allocator<void> > SetChargeRequest;

typedef boost::shared_ptr< ::auto_charging::SetChargeRequest > SetChargeRequestPtr;
typedef boost::shared_ptr< ::auto_charging::SetChargeRequest const> SetChargeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_charging::SetChargeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_charging::SetChargeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::auto_charging::SetChargeRequest_<ContainerAllocator1> & lhs, const ::auto_charging::SetChargeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.nav == rhs.nav &&
    lhs.ar_track == rhs.ar_track &&
    lhs.ar_id == rhs.ar_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::auto_charging::SetChargeRequest_<ContainerAllocator1> & lhs, const ::auto_charging::SetChargeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace auto_charging

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::auto_charging::SetChargeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_charging::SetChargeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_charging::SetChargeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_charging::SetChargeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_charging::SetChargeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_charging::SetChargeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_charging::SetChargeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "171717c025d6d110ac13d9375abafd0c";
  }

  static const char* value(const ::auto_charging::SetChargeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x171717c025d6d110ULL;
  static const uint64_t static_value2 = 0xac13d9375abafd0cULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_charging::SetChargeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_charging/SetChargeRequest";
  }

  static const char* value(const ::auto_charging::SetChargeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_charging::SetChargeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool nav\n"
"bool ar_track \n"
"int8 ar_id\n"
;
  }

  static const char* value(const ::auto_charging::SetChargeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_charging::SetChargeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nav);
      stream.next(m.ar_track);
      stream.next(m.ar_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetChargeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_charging::SetChargeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_charging::SetChargeRequest_<ContainerAllocator>& v)
  {
    s << indent << "nav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nav);
    s << indent << "ar_track: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ar_track);
    s << indent << "ar_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ar_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_CHARGING_MESSAGE_SETCHARGEREQUEST_H
