// Generated by gencpp from file auto_charging/SetChargeResponse.msg
// DO NOT EDIT!


#ifndef AUTO_CHARGING_MESSAGE_SETCHARGERESPONSE_H
#define AUTO_CHARGING_MESSAGE_SETCHARGERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_charging
{
template <class ContainerAllocator>
struct SetChargeResponse_
{
  typedef SetChargeResponse_<ContainerAllocator> Type;

  SetChargeResponse_()
    : message()
    , success(false)  {
    }
  SetChargeResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::auto_charging::SetChargeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_charging::SetChargeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetChargeResponse_

typedef ::auto_charging::SetChargeResponse_<std::allocator<void> > SetChargeResponse;

typedef boost::shared_ptr< ::auto_charging::SetChargeResponse > SetChargeResponsePtr;
typedef boost::shared_ptr< ::auto_charging::SetChargeResponse const> SetChargeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_charging::SetChargeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_charging::SetChargeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::auto_charging::SetChargeResponse_<ContainerAllocator1> & lhs, const ::auto_charging::SetChargeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::auto_charging::SetChargeResponse_<ContainerAllocator1> & lhs, const ::auto_charging::SetChargeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace auto_charging

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::auto_charging::SetChargeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_charging::SetChargeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_charging::SetChargeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_charging::SetChargeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_charging::SetChargeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_charging::SetChargeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_charging::SetChargeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bf829f07d795d3f9e541a07897da2c4";
  }

  static const char* value(const ::auto_charging::SetChargeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bf829f07d795d3fULL;
  static const uint64_t static_value2 = 0x9e541a07897da2c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_charging::SetChargeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_charging/SetChargeResponse";
  }

  static const char* value(const ::auto_charging::SetChargeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_charging::SetChargeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"bool success \n"
;
  }

  static const char* value(const ::auto_charging::SetChargeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_charging::SetChargeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetChargeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_charging::SetChargeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_charging::SetChargeResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_CHARGING_MESSAGE_SETCHARGERESPONSE_H
