// Generated by gencpp from file auto_charging/SetCharge.msg
// DO NOT EDIT!


#ifndef AUTO_CHARGING_MESSAGE_SETCHARGE_H
#define AUTO_CHARGING_MESSAGE_SETCHARGE_H

#include <ros/service_traits.h>


#include <auto_charging/SetChargeRequest.h>
#include <auto_charging/SetChargeResponse.h>


namespace auto_charging
{

struct SetCharge
{

typedef SetChargeRequest Request;
typedef SetChargeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCharge
} // namespace auto_charging


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::auto_charging::SetCharge > {
  static const char* value()
  {
    return "3584daae5e4de369ae6b70e57de9d866";
  }

  static const char* value(const ::auto_charging::SetCharge&) { return value(); }
};

template<>
struct DataType< ::auto_charging::SetCharge > {
  static const char* value()
  {
    return "auto_charging/SetCharge";
  }

  static const char* value(const ::auto_charging::SetCharge&) { return value(); }
};


// service_traits::MD5Sum< ::auto_charging::SetChargeRequest> should match
// service_traits::MD5Sum< ::auto_charging::SetCharge >
template<>
struct MD5Sum< ::auto_charging::SetChargeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::auto_charging::SetCharge >::value();
  }
  static const char* value(const ::auto_charging::SetChargeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_charging::SetChargeRequest> should match
// service_traits::DataType< ::auto_charging::SetCharge >
template<>
struct DataType< ::auto_charging::SetChargeRequest>
{
  static const char* value()
  {
    return DataType< ::auto_charging::SetCharge >::value();
  }
  static const char* value(const ::auto_charging::SetChargeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::auto_charging::SetChargeResponse> should match
// service_traits::MD5Sum< ::auto_charging::SetCharge >
template<>
struct MD5Sum< ::auto_charging::SetChargeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::auto_charging::SetCharge >::value();
  }
  static const char* value(const ::auto_charging::SetChargeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_charging::SetChargeResponse> should match
// service_traits::DataType< ::auto_charging::SetCharge >
template<>
struct DataType< ::auto_charging::SetChargeResponse>
{
  static const char* value()
  {
    return DataType< ::auto_charging::SetCharge >::value();
  }
  static const char* value(const ::auto_charging::SetChargeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTO_CHARGING_MESSAGE_SETCHARGE_H
