# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rei_robot_base/CarData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class CarData(genpy.Message):
  _md5sum = "857f5bd49eb52154124a6a34972c8da9"
  _type = "rei_robot_base/CarData"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
float64[] motor_speed
int8[] crash
int8[] cliff
float32[] ultrasound
int8 smoke
float32 power_voltage
bool is_charge
float32 tempareture
float32 relative_humidity
int8[4] input_io
int8[7] output_io
bool relay_status

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','motor_speed','crash','cliff','ultrasound','smoke','power_voltage','is_charge','tempareture','relative_humidity','input_io','output_io','relay_status']
  _slot_types = ['std_msgs/Header','float64[]','int8[]','int8[]','float32[]','int8','float32','bool','float32','float32','int8[4]','int8[7]','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,motor_speed,crash,cliff,ultrasound,smoke,power_voltage,is_charge,tempareture,relative_humidity,input_io,output_io,relay_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CarData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.motor_speed is None:
        self.motor_speed = []
      if self.crash is None:
        self.crash = []
      if self.cliff is None:
        self.cliff = []
      if self.ultrasound is None:
        self.ultrasound = []
      if self.smoke is None:
        self.smoke = 0
      if self.power_voltage is None:
        self.power_voltage = 0.
      if self.is_charge is None:
        self.is_charge = False
      if self.tempareture is None:
        self.tempareture = 0.
      if self.relative_humidity is None:
        self.relative_humidity = 0.
      if self.input_io is None:
        self.input_io = [0] * 4
      if self.output_io is None:
        self.output_io = [0] * 7
      if self.relay_status is None:
        self.relay_status = False
    else:
      self.header = std_msgs.msg.Header()
      self.motor_speed = []
      self.crash = []
      self.cliff = []
      self.ultrasound = []
      self.smoke = 0
      self.power_voltage = 0.
      self.is_charge = False
      self.tempareture = 0.
      self.relative_humidity = 0.
      self.input_io = [0] * 4
      self.output_io = [0] * 7
      self.relay_status = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.motor_speed)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.motor_speed))
      length = len(self.crash)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(struct.Struct(pattern).pack(*self.crash))
      length = len(self.cliff)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(struct.Struct(pattern).pack(*self.cliff))
      length = len(self.ultrasound)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.ultrasound))
      _x = self
      buff.write(_get_struct_bfB2f().pack(_x.smoke, _x.power_voltage, _x.is_charge, _x.tempareture, _x.relative_humidity))
      buff.write(_get_struct_4b().pack(*self.input_io))
      buff.write(_get_struct_7b().pack(*self.output_io))
      _x = self.relay_status
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.motor_speed = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.crash = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.cliff = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.ultrasound = s.unpack(str[start:end])
      _x = self
      start = end
      end += 14
      (_x.smoke, _x.power_voltage, _x.is_charge, _x.tempareture, _x.relative_humidity,) = _get_struct_bfB2f().unpack(str[start:end])
      self.is_charge = bool(self.is_charge)
      start = end
      end += 4
      self.input_io = _get_struct_4b().unpack(str[start:end])
      start = end
      end += 7
      self.output_io = _get_struct_7b().unpack(str[start:end])
      start = end
      end += 1
      (self.relay_status,) = _get_struct_B().unpack(str[start:end])
      self.relay_status = bool(self.relay_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.motor_speed)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.motor_speed.tostring())
      length = len(self.crash)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(self.crash.tostring())
      length = len(self.cliff)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(self.cliff.tostring())
      length = len(self.ultrasound)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.ultrasound.tostring())
      _x = self
      buff.write(_get_struct_bfB2f().pack(_x.smoke, _x.power_voltage, _x.is_charge, _x.tempareture, _x.relative_humidity))
      buff.write(self.input_io.tostring())
      buff.write(self.output_io.tostring())
      _x = self.relay_status
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.motor_speed = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.crash = numpy.frombuffer(str[start:end], dtype=numpy.int8, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.cliff = numpy.frombuffer(str[start:end], dtype=numpy.int8, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.ultrasound = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 14
      (_x.smoke, _x.power_voltage, _x.is_charge, _x.tempareture, _x.relative_humidity,) = _get_struct_bfB2f().unpack(str[start:end])
      self.is_charge = bool(self.is_charge)
      start = end
      end += 4
      self.input_io = numpy.frombuffer(str[start:end], dtype=numpy.int8, count=4)
      start = end
      end += 7
      self.output_io = numpy.frombuffer(str[start:end], dtype=numpy.int8, count=7)
      start = end
      end += 1
      (self.relay_status,) = _get_struct_B().unpack(str[start:end])
      self.relay_status = bool(self.relay_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4b = None
def _get_struct_4b():
    global _struct_4b
    if _struct_4b is None:
        _struct_4b = struct.Struct("<4b")
    return _struct_4b
_struct_7b = None
def _get_struct_7b():
    global _struct_7b
    if _struct_7b is None:
        _struct_7b = struct.Struct("<7b")
    return _struct_7b
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_bfB2f = None
def _get_struct_bfB2f():
    global _struct_bfB2f
    if _struct_bfB2f is None:
        _struct_bfB2f = struct.Struct("<bfB2f")
    return _struct_bfB2f
