(cl:defpackage rei_robot_cruise-srv
  (:use )
  (:export
   "REMOVEGOAL"
   "<REMOVEGOAL-REQUEST>"
   "REMOVEGOAL-REQUEST"
   "<REMOVEGOAL-RESPONSE>"
   "REMOVEGOAL-RESPONSE"
   "SETGOALS"
   "<SETGOALS-REQUEST>"
   "SETGOALS-REQUEST"
   "<SETGOALS-RESPONSE>"
   "SETGOALS-RESPONSE"
   "SETNAVORDER"
   "<SETNAVORDER-REQUEST>"
   "SETNAVORDER-REQUEST"
   "<SETNAVORDER-RESPONSE>"
   "SETNAVORDER-RESPONSE"
   "STARTSTOPNAV"
   "<STARTSTOPNAV-REQUEST>"
   "STARTSTOPNAV-REQUEST"
   "<STARTSTOPNAV-RESPONSE>"
   "STARTSTOPNAV-RESPONSE"
  ))

